OPENAI_API_KEY="sk-proj-4cGDxq3H0kMVzdVUgYqnT3BlbkFJuzOUg6NcU4P28q9Y6Ini"
ASSISTANT_ID_v1="asst_4mCtSgoUxLP2pkbeO2AxfiOx"
ASSISTANT_ID_v2="asst_QVeIpketO4qR8ex6OrctHCuP"
ASSISTANT_ID="asst_xVhK3VmUfh8brqSOgzLPCR1c"
TC_SERVER_IP="192.168.1.66"
TC_SERVER_PORT="8080"
LHR_SERVER="https://ef20816eef21dc.lhr.life"
BARCHART_TEMPLATE="https://storage.googleapis.com/example_bucekt/BarChartTemplate.pptx"